#!/usr/bin/env bash

mkdir -p ~/.vim
mkdir -p ~/.config/nvim

VIM_FOLDERS=(
    "autoload"
    "plugin"
    "colors"
    "ftdetect"
    "ftplugin"
    "indent"
    "compiler"
    "after"
    "doc"
)

cd ~/.vim

for fd in ${VIM_FOLDERS[@]}
do
    mkdir -p ./$fd
done

cd -

_dotfiles_utils_check_brew
if ! command -v fnm &> /dev/null
then
    brew install fnm
fi

if ! command -v node &> /dev/null
then
    fnm install $(fnm list-remote | tail -n 1)
fi
