#!/usr/bin/env sh

# shellcheck disable=SC2034

# {{{ Env Vars -----------------------------------------------------------------------

PLUGINS="$HOME/.config/sketchybar/plugins"
COL_BLACK='2e3440'
COL_LIGHT_BLACK='3b4252'
COL_GREY='434c5e'
COL_LIGHT_GREY='4c566a'
COL_DARK_WHITE='d8dee9'
COL_WHITE='e5e9f0'
COL_SNOW_WHITE='eceff4'
COL_TEAL_GREEN='8fbcbb'
COL_TEAL='88c0d0'
COL_SKY_BLUE='81a1c1'
COL_BLUE='5e81ac'
COL_RED='bf616a'
COL_ORANGE='d08770'
COL_YELLOW='ebcb8b'
COL_GREEN='a3be8c'
COL_PURPLE='b48ead'

# }}}
# {{{ BAR -----------------------------------------------------------------------

sketchybar -m --bar height=32 \
	blur_radius=0 \
	position=top \
	padding_left=8 \
	padding_right=8 \
	margin=0 \
	corner_radius=0 \
	color=0x00000000 \
	border_width=0 \
	y_offset=4 \
	display=all
# }}}
# {{{ Defaults -----------------------------------------------------------

sketchybar -m --default updates=when_shown \
	drawing=on \
	icon.font="Hack Nerd Font:Bold:18.0" \
	icon.color="0xff${COL_SNOW_WHITE}" \
	icon.highlight_color="0xff${COL_GREEN}" \
	label.font="Hack Nerd Font:Bold:16.0" \
	label.color="0xff${COL_SNOW_WHITE}" \
  background.height=30

sketchybar -m --default label.padding_left=0 \
	label.padding_right=0 \
	icon.padding_left=8 \
	icon.padding_right=8

# }}}
# {{{ Left ----------------------------------------------------------------------
# {{{ Desktop spaces
sketchybar -m --add item logo left \
	--set logo icon= \
	background.corner_radius=4 \
	background.color="0xff${COL_GREEN}" \
	associated_display=1

. "$HOME/.config/sketchybar/items/yabai_spaces.sh"

# }}}
# {{{ Yabai layout modes
sketchybar -m --add item sep left \
	--set sep icon="" \
	associated_display=1

sketchybar -m --add item yabai_icon left \
	--set yabai_icon \
	icon= \
	background.color="0xff${COL_LIGHT_GREY}" \
	background.corner_radius=4 \
	associated_display=1

sketchybar -m --add item yabai_bsp left \
	--set yabai_bsp \
	update_freq=3 \
	icon= \
	script="$PLUGINS/yabai_mode.sh" \
  click_script="$PLUGINS/yabai_click.sh" \
	associated_display=1 \
	--subscribe yabai_bsp space_change

sketchybar -m --add item yabai_float left \
	--set yabai_float \
	update_freq=3 \
	icon=  \
	script="$PLUGINS/yabai_mode.sh" \
  click_script="$PLUGINS/yabai_click.sh" \
	associated_display=1 \
	--subscribe yabai_float space_change


sketchybar -m --add item yabai_stack left \
	--set yabai_stack \
	update_freq=3 \
	icon=﯅ \
	script="$PLUGINS/yabai_mode.sh" \
  click_script="$PLUGINS/yabai_click.sh" \
	associated_display=1 \
	--subscribe yabai_stack space_change

sketchybar --add bracket _yabai \
	yabai_icon \
	yabai_bsp \
	yabai_float \
	yabai_stack \
	--set _yabai \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_LIGHT_GREY}" \
	background.border_width=2 \
	background.corner_radius=4
# }}}
# }}}
# {{{ MIDDLE --------------------------------------------------------------------

sketchybar --add item system.label center \
	--set system.label script="$PLUGINS/title.sh" \
	associated_display=1 \
	--subscribe system.label front_app_switched

# }}}
# {{{ RIGHT ---------------------------------------------------------------------

sketchybar -m --add item time_label right \
	--set time_label \
	update_freq=5 \
	label.padding_right=8 \
	icon.padding_left=0 \
	icon.padding_right=4 \
	script="$PLUGINS/time.sh" \
	associated_display=1

sketchybar -m --add item time_icon right \
	--set time_icon icon= \
	background.color="0xff${COL_BLUE}" \
	background.corner_radius=4 \
	associated_display=1

sketchybar -m --add item sep1 right \
	--set sep1 \
	icon.drawing=off \
	label.drawing=off \
	width=10 \
	associated_display=1

sketchybar -m --add item date_label right \
	--set date_label \
	update_freq=60 \
	label.padding_right=8 \
	icon.padding_left=0 \
	icon.padding_right=4 \
	script="$PLUGINS/date.sh" \
	associated_display=1

sketchybar -m --add item date_icon right \
	--set date_icon icon= \
	background.color="0xff${COL_YELLOW}" \
	background.corner_radius=4 \
	associated_display=1

sketchybar -m --add item sep2 right \
	--set sep2 \
	icon.drawing=off \
	label.drawing=off \
	width=10 \
	associated_display=1

sketchybar -m --add item battery_label right \
	--set battery_label \
	update_freq=10 \
	label.padding_right=8 \
	icon.padding_left=0 \
	icon.padding_right=4 \
	script="$PLUGINS/battery.sh" \
	associated_display=1

sketchybar -m --add item battery_icon right \
	--set battery_icon \
	background.color="0xff${COL_PURPLE}" \
	background.corner_radius=4 \
	update_freq=10 \
	script="$PLUGINS/battery_icon.sh" \
	associated_display=1

sketchybar -m --add item sep3 right \
	--set sep3 \
	icon.drawing=off \
	label.drawing=off \
	width=10 \
	associated_display=1

sketchybar -m --add item volume_label right \
	--set volume_label \
	update_freq=3 \
	label.padding_right=8 \
	icon.padding_left=0 \
	icon.padding_right=4 \
	script="$PLUGINS/volume.sh" \
	associated_display=1

sketchybar -m --add item volume_icon right \
	--set volume_icon \
	update_freq=3 \
	background.color="0xff${COL_TEAL_GREEN}" \
	background.corner_radius=4 \
	script="$PLUGINS/volume_icon.sh" \
	associated_display=1

sketchybar -m --add item sep4 right \
	--set sep4 \
	icon.drawing=off \
	label.drawing=off \
	width=10 \
	associated_display=1

sketchybar -m --add item network_label right \
	--set network_label \
	update_freq=10 \
	icon= \
	icon.color="0xff${COL_BLACK}" \
	icon.font="Hack Nerd Font:Bold:15.0" \
	icon.padding_left=7 \
	icon.padding_right=4 \
	label.color="0xff${COL_BLACK}" \
	label.font="Hack Nerd Font:Bold:12.0" \
	label.padding_left=0 \
	label.padding_right=8 \
	background.color="0xff${COL_BLUE}" \
	background.height=24 \
	background.corner_radius=6 \
	script="$PLUGINS/network.sh" \
	associated_display=1

sketchybar --add bracket _time \
	time_label \
	time_icon \
	--set _time \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_BLUE}" \
	background.border_width=2 \
	background.corner_radius=4

sketchybar --add bracket _date \
	date_label \
	date_icon \
	--set _date \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_YELLOW}" \
	background.border_width=2 \
	background.corner_radius=4

sketchybar --add bracket _battery \
	battery_label \
	battery_icon \
	--set _battery \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_PURPLE}" \
	background.border_width=2 \
	background.corner_radius=4

sketchybar --add bracket _volume \
	volume_label \
	volume_icon \
	--set _volume \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_TEAL_GREEN}" \
	background.border_width=2 \
	background.corner_radius=4

sketchybar --add bracket _network \
	network_label \
	--set _network \
	background.color="0xff${COL_BLACK}" \
	background.border_color="0xff${COL_RED}" \
	background.border_width=2 \
	background.corner_radius=4

sketchybar -m --add item sep5 right \
	--set sep5 \
	icon.drawing=off \
	label.drawing=off \
	width=10 \
	associated_display=1

. "$HOME/.config/sketchybar/items/weather.sh"

. "$HOME/.config/sketchybar/items/stats.sh"

# }}}

# {{{ MAIN DISPLAY - Cursor Usage -------------------------------------------

. "$HOME/.config/sketchybar/items/cursor_usage.sh"

# }}}

# {{{ SECONDARY DISPLAY - CI Status Monitor ----------------------------------
# Main item with popup for detailed PR list (click to expand)

sketchybar --add item bk_status left \
	--set bk_status \
	icon=󰊤 \
	icon.font="Hack Nerd Font:Bold:16.0" \
	icon.color="0xff${COL_GREEN}" \
	icon.padding_left=10 \
	icon.padding_right=6 \
	label="Loading..." \
	label.font="Hack Nerd Font:Bold:12.0" \
	label.color="0xff${COL_SNOW_WHITE}" \
	label.padding_right=10 \
	background.color="0xff${COL_BLACK}" \
	background.height=28 \
	background.corner_radius=6 \
	background.border_color="0xff${COL_GREEN}" \
	background.border_width=2 \
	popup.background.color="0xff${COL_BLACK}" \
	popup.background.corner_radius=8 \
	popup.background.border_color="0xff${COL_GREEN}" \
	popup.background.border_width=2 \
	associated_display=2 \
	update_freq=30 \
	script="$PLUGINS/buildkite.sh" \
	click_script="sketchybar --set bk_status popup.drawing=toggle"

# Popup items (shown vertically when clicking main item)
sketchybar --add item bk_pr1 popup.bk_status \
	--set bk_pr1 \
	icon=● \
	icon.font="Hack Nerd Font:Bold:10.0" \
	icon.color="0xff${COL_GREEN}" \
	icon.padding_left=10 \
	icon.padding_right=8 \
	label="PR #1" \
	label.font="Hack Nerd Font:Regular:12.0" \
	label.color="0xff${COL_SNOW_WHITE}" \
	label.padding_right=10 \
	background.color="0xff${COL_LIGHT_BLACK}" \
	background.height=28 \
	background.corner_radius=4 \
	background.padding_left=5 \
	background.padding_right=5 \
	drawing=off \
	click_script="$PLUGINS/buildkite_click.sh 1"

sketchybar --add item bk_pr2 popup.bk_status \
	--set bk_pr2 \
	icon=● \
	icon.font="Hack Nerd Font:Bold:10.0" \
	icon.color="0xff${COL_GREEN}" \
	icon.padding_left=10 \
	icon.padding_right=8 \
	label="PR #2" \
	label.font="Hack Nerd Font:Regular:12.0" \
	label.color="0xff${COL_SNOW_WHITE}" \
	label.padding_right=10 \
	background.color="0xff${COL_LIGHT_BLACK}" \
	background.height=28 \
	background.corner_radius=4 \
	background.padding_left=5 \
	background.padding_right=5 \
	drawing=off \
	click_script="$PLUGINS/buildkite_click.sh 2"

sketchybar --add item bk_pr3 popup.bk_status \
	--set bk_pr3 \
	icon=● \
	icon.font="Hack Nerd Font:Bold:10.0" \
	icon.color="0xff${COL_GREEN}" \
	icon.padding_left=10 \
	icon.padding_right=8 \
	label="PR #3" \
	label.font="Hack Nerd Font:Regular:12.0" \
	label.color="0xff${COL_SNOW_WHITE}" \
	label.padding_right=10 \
	background.color="0xff${COL_LIGHT_BLACK}" \
	background.height=28 \
	background.corner_radius=4 \
	background.padding_left=5 \
	background.padding_right=5 \
	drawing=off \
	click_script="$PLUGINS/buildkite_click.sh 3"

# }}}

sketchybar -m --update
echo "sketchybar configuration loaded.."

# vim: foldmethod=marker foldlevel=0
