#!/usr/bin/env bash

mkdir -p ~/.config/fish/functions
mkdir -p ~/.config/fish/conf.d
mkdir -p ~/.config/fish/completions

if ! command -v fzf &> /dev/null
  then
    if [[ "$OSTYPE" == "darwin"* ]]; then
        brew install fzf
    else
        echo "Not running on macOS - please install fzf through your system's package manager"
        exit 1
    fi
fi

